sudo: false
language: php
cache:
  directories:
    - $HOME/.composer/cache/files
php:
  - 5.6
  - 7.0
  - 7.2
  - 7.4
before_install:
  ## Disabling xdebug
  - phpenv config-rm xdebug.ini
install:
  # Update composer, install dependencies
  - flags="--ansi --prefer-dist --no-interaction --optimize-autoloader --no-suggest --no-progress"
  - composer self-update
  - composer install $flags
script:
  - vendor/atoum/atoum/bin/atoum -d tests/units/ --use-light-report
  - vendor/bin/php-cs-fixer --diff --dry-run -v fix
